export const CATEGORY_BLURBS: Record<string, string> = {
  "medical-disposables": "Gloves, masks, caps and everyday consumables.",
  "ppe-safety": "Protective equipment for healthcare and everyday use.",
  "wound-care": "Dressings, bandages and wound-care supplies.",
  "surgical-supplies": "Instruments, sutures and surgical accessories.",
  "diagnostic-equipment": "Blood-pressure monitors, stethoscopes and examination equipment.",
  "patient-monitoring": "Monitors, sensors and monitoring accessories.",
  "mobility-rehabilitation": "Crutches and mobility-support products.",
  "orthopedic-supports": "Braces, supports and splints.",
  "laboratory-supplies": "Collection, consumables and laboratory equipment.",
  "injection-sampling": "Syringes, needles and sampling supplies.",
  "infusion-iv": "IV sets, cannulas and infusion accessories.",
  "respiratory-care": "Nebulizers, oxygen masks and respiratory supplies.",
  "emergency-first-aid": "First aid kits and emergency supplies.",
  "hospital-equipment": "Beds, trolleys and clinical equipment.",
  "medical-furniture": "Examination couches, stools and storage.",
  "sterilization": "Sterilization and infection-control supplies.",
  "medical-hygiene": "Hand hygiene, wipes and personal-care supplies.",
  "dental-supplies": "Dental examination and consumable supplies.",
  "maternal-child-care": "Maternity and infant-care supplies.",
  "home-healthcare": "Home monitoring, mobility and care supplies.",
  "patient-care": "Patient hygiene, transfer and care supplies.",
  "medical-accessories": "Bags, accessories and general supplies.",
};
