export type MasterCategory = {
  name: string;
  slug: string;
  isActive: boolean;
  subcategories: string[];
};

export const MASTER_TAXONOMY: MasterCategory[] = [
  {
    name: "Medical Disposables & Consumables",
    slug: "medical-disposables",
    isActive: true,
    subcategories: [
      "Examination Gloves",
      "Surgical Gloves",
      "Disposable Gloves",
      "Face Masks",
      "Surgical Masks",
      "3-Ply Masks",
      "Disposable Masks",
      "Respirator Masks",
      "Medical Caps",
      "Shoe Covers",
      "Disposable Gowns",
      "Disposable Aprons",
      "Disposable Sleeves",
      "Disposable Sheets",
      "Disposable Underpads",
      "Surgical Drapes",
      "Disposable Surgical Packs",
      "Cotton Products",
      "Cotton Wool",
      "Cotton Balls",
      "Cotton Rolls",
      "Gauze",
      "Gauze Swabs",
      "Sterile Gauze",
      "Non-Sterile Gauze",
      "Medical Tape",
      "Adhesive Tape",
      "Micropore Tape",
      "Surgical Tape",
      "Tongue Depressors",
      "Applicators",
      "Disposable Cups",
      "Medical Waste Bags",
      "Sharps Containers",
      "Other Medical Disposables",
    ],
  },
  {
    name: "PPE & Safety Products",
    slug: "ppe-safety",
    isActive: true,
    subcategories: [
      "Examination Gloves",
      "Surgical Gloves",
      "Nitrile Gloves",
      "Latex Gloves",
      "Vinyl Gloves",
      "Face Masks",
      "Respirator Masks",
      "Protective Gowns",
      "Isolation Gowns",
      "Aprons",
      "Shoe Covers",
      "Head Covers",
      "Face Shields",
      "Protective Goggles",
      "Safety Goggles",
      "Protective Sleeves",
      "Hand Protection",
      "Body Protection",
      "Infection Prevention Supplies",
      "Hand Sanitizers",
      "Disinfectants",
      "Surface Disinfection Products",
      "Biohazard Bags",
      "Sharps Disposal",
      "Other PPE & Safety Products",
    ],
  },
  {
    name: "Wound Care & Dressings",
    slug: "wound-care",
    isActive: true,
    subcategories: [
      "Adhesive Bandages",
      "Plasters",
      "Gauze Dressings",
      "Sterile Dressings",
      "Non-Sterile Dressings",
      "Wound Pads",
      "Absorbent Dressings",
      "Compression Bandages",
      "Elastic Bandages",
      "Crepe Bandages",
      "Roller Bandages",
      "Triangular Bandages",
      "Cohesive Bandages",
      "Wound Tapes",
      "Medical Cotton",
      "Cotton Wool",
      "Antiseptic Wound Supplies",
      "Burn Dressings",
      "Eye Dressings",
      "Wound Care Kits",
      "Other Wound Care Supplies",
    ],
  },
  {
    name: "Surgical Supplies & Instruments",
    slug: "surgical-supplies",
    isActive: true,
    subcategories: [
      "Surgical Instruments",
      "Scissors",
      "Forceps",
      "Hemostats",
      "Clamps",
      "Retractors",
      "Needle Holders",
      "Speculums",
      "Surgical Knives",
      "Surgical Blades",
      "Surgical Needles",
      "Surgical Sutures",
      "Surgical Drapes",
      "Surgical Gowns",
      "Surgical Packs",
      "Surgical Trays",
      "Sterilization Supplies",
      "Instrument Containers",
      "Surgical Accessories",
      "Other Surgical Supplies",
    ],
  },
  {
    name: "Diagnostic & Examination Equipment",
    slug: "diagnostic-equipment",
    isActive: true,
    subcategories: [
      "Stethoscopes",
      "Blood Pressure Monitors",
      "Manual BP Monitors",
      "Digital BP Monitors",
      "Blood Pressure Cuffs",
      "Thermometers",
      "Digital Thermometers",
      "Infrared Thermometers",
      "Pulse Oximeters",
      "Glucose Meters",
      "Glucose Testing Supplies",
      "Examination Lights",
      "Otoscopes",
      "Ophthalmoscopes",
      "Reflex Hammers",
      "Measuring Equipment",
      "Medical Scales",
      "Height Measuring Equipment",
      "Examination Kits",
      "Diagnostic Accessories",
      "Other Diagnostic Equipment",
    ],
  },
  {
    name: "Patient Monitoring",
    slug: "patient-monitoring",
    isActive: true,
    subcategories: [
      "Patient Monitors",
      "Vital Signs Monitors",
      "Pulse Oximetry",
      "Blood Pressure Monitoring",
      "Temperature Monitoring",
      "ECG Equipment",
      "ECG Electrodes",
      "Monitoring Cables",
      "Monitoring Sensors",
      "Monitoring Accessories",
      "Other Patient Monitoring Equipment",
    ],
  },
  {
    name: "Mobility & Rehabilitation",
    slug: "mobility-rehabilitation",
    isActive: true,
    subcategories: [
      "Crutches",
      "Axillary Crutches",
      "Elbow/Forearm Crutches",
      "Walking Frames",
      "Walkers",
      "Walking Sticks",
      "Canes",
      "Wheelchairs",
      "Commode Chairs",
      "Transfer Aids",
      "Mobility Accessories",
      "Rehabilitation Equipment",
      "Exercise & Therapy Equipment",
      "Resistance Bands",
      "Therapy Balls",
      "Rehabilitation Accessories",
      "Other Mobility Equipment",
    ],
  },
  {
    name: "Orthopedic Supports & Braces",
    slug: "orthopedic-supports",
    isActive: true,
    subcategories: [
      "Knee Supports",
      "Knee Braces",
      "Ankle Supports",
      "Ankle Braces",
      "Wrist Supports",
      "Wrist Braces",
      "Elbow Supports",
      "Elbow Braces",
      "Back Supports",
      "Lumbar Supports",
      "Neck Supports",
      "Cervical Collars",
      "Shoulder Supports",
      "Arm Slings",
      "Wrist Splints",
      "Finger Splints",
      "Leg Supports",
      "Compression Supports",
      "Orthopedic Accessories",
      "Other Orthopedic Products",
    ],
  },
  {
    name: "Laboratory Supplies",
    slug: "laboratory-supplies",
    isActive: true,
    subcategories: [
      "Specimen Collection",
      "Specimen Containers",
      "Sample Bottles",
      "Urine Containers",
      "Stool Containers",
      "Swabs",
      "Blood Collection",
      "Blood Collection Tubes",
      "Blood Collection Accessories",
      "Lancets",
      "Test Tubes",
      "Test Tube Accessories",
      "Sample Racks",
      "Petri Dishes",
      "Microscope Slides",
      "Cover Slips",
      "Pipettes",
      "Pipette Tips",
      "Laboratory Consumables",
      "Laboratory Glassware",
      "Laboratory Plasticware",
      "Laboratory Safety Products",
      "Laboratory Equipment",
      "Centrifuges",
      "Microscopes",
      "Laboratory Scales",
      "Laboratory Storage",
      "Other Laboratory Supplies",
    ],
  },
  {
    name: "Injection & Sampling Supplies",
    slug: "injection-sampling",
    isActive: true,
    subcategories: [
      "Syringes",
      "Needles",
      "Insulin Syringes",
      "Injection Accessories",
      "Lancets",
      "Blood Collection Tubes",
      "Blood Collection Needles",
      "Tourniquets",
      "Alcohol Swabs",
      "Specimen Containers",
      "Sample Collection Kits",
      "Other Injection & Sampling Supplies",
    ],
  },
  {
    name: "Infusion & IV Supplies",
    slug: "infusion-iv",
    isActive: true,
    subcategories: [
      "IV Sets",
      "IV Cannulas",
      "IV Catheters",
      "Extension Sets",
      "Three-Way Stopcocks",
      "IV Connectors",
      "Infusion Accessories",
      "Infusion Pumps",
      "Infusion Pump Accessories",
      "IV Stands",
      "Tourniquets",
      "Other IV Supplies",
    ],
  },
  {
    name: "Respiratory Care",
    slug: "respiratory-care",
    isActive: true,
    subcategories: [
      "Nebulizers",
      "Nebulizer Masks",
      "Nebulizer Accessories",
      "Oxygen Masks",
      "Oxygen Tubing",
      "Nasal Cannulas",
      "Respiratory Masks",
      "Breathing Circuits",
      "Suction Catheters",
      "Suction Accessories",
      "Oxygen Accessories",
      "Respiratory Care Equipment",
      "Other Respiratory Supplies",
    ],
  },
  {
    name: "Emergency & First Aid",
    slug: "emergency-first-aid",
    isActive: true,
    subcategories: [
      "First Aid Kits",
      "First Aid Boxes",
      "Trauma Kits",
      "Emergency Kits",
      "Bandages",
      "Plasters",
      "Gauze",
      "Adhesive Tape",
      "Scissors",
      "Emergency Blankets",
      "CPR Masks",
      "First Aid Accessories",
      "Emergency Supplies",
      "Other Emergency Products",
    ],
  },
  {
    name: "Hospital & Clinical Equipment",
    slug: "hospital-equipment",
    isActive: true,
    subcategories: [
      "Examination Tables",
      "Examination Couches",
      "Hospital Beds",
      "Patient Beds",
      "Stretchers",
      "Wheelchairs",
      "Bedside Cabinets",
      "Medical Trolleys",
      "Procedure Trolleys",
      "Instrument Trolleys",
      "Treatment Carts",
      "IV Stands",
      "Medical Stools",
      "Examination Stools",
      "Privacy Screens",
      "Patient Chairs",
      "Medical Storage",
      "Hospital Furniture",
      "Other Hospital Equipment",
    ],
  },
  {
    name: "Medical Furniture",
    slug: "medical-furniture",
    isActive: true,
    subcategories: [
      "Examination Beds",
      "Examination Couches",
      "Examination Chairs",
      "Treatment Chairs",
      "Medical Stools",
      "Hospital Beds",
      "Bedside Lockers",
      "Medical Cabinets",
      "Medical Shelving",
      "Medical Trolleys",
      "Instrument Tables",
      "IV Stands",
      "Privacy Screens",
      "Waiting Room Furniture",
      "Other Medical Furniture",
    ],
  },
  {
    name: "Sterilization & Infection Control",
    slug: "sterilization",
    isActive: true,
    subcategories: [
      "Autoclaves",
      "Sterilizers",
      "Sterilization Pouches",
      "Sterilization Rolls",
      "Sterilization Containers",
      "Instrument Trays",
      "Instrument Containers",
      "Disinfectants",
      "Surface Disinfectants",
      "Hand Hygiene Products",
      "Hand Sanitizers",
      "Antiseptic Products",
      "Infection Control Supplies",
      "Biohazard Bags",
      "Sharps Containers",
      "Other Sterilization Supplies",
    ],
  },
  {
    name: "Medical Hygiene & Personal Care",
    slug: "medical-hygiene",
    isActive: true,
    subcategories: [
      "Hand Sanitizers",
      "Hand Wash",
      "Disinfectants",
      "Antiseptic Products",
      "Wet Wipes",
      "Medical Wipes",
      "Adult Care Products",
      "Incontinence Products",
      "Disposable Underpads",
      "Personal Hygiene Supplies",
      "Other Hygiene Products",
    ],
  },
  {
    name: "Dental Supplies",
    slug: "dental-supplies",
    isActive: false,
    subcategories: [
      "Dental Examination",
      "Dental Gloves",
      "Dental Masks",
      "Dental Instruments",
      "Dental Consumables",
      "Dental Bibs",
      "Dental Suction Products",
      "Dental Impression Supplies",
      "Dental Accessories",
      "Other Dental Supplies",
    ],
  },
  {
    name: "Maternal & Child Care",
    slug: "maternal-child-care",
    isActive: false,
    subcategories: [
      "Maternity Supplies",
      "Baby Care Supplies",
      "Infant Care",
      "Breastfeeding Accessories",
      "Disposable Baby Products",
      "Newborn Care Supplies",
      "Other Maternal & Child Care",
    ],
  },
  {
    name: "Home Healthcare",
    slug: "home-healthcare",
    isActive: true,
    subcategories: [
      "Home Blood Pressure Monitors",
      "Digital Thermometers",
      "Pulse Oximeters",
      "Glucose Monitoring",
      "Nebulizers",
      "Mobility Aids",
      "Wheelchairs",
      "Walkers",
      "Crutches",
      "Home First Aid Kits",
      "Home Care Supplies",
      "Patient Care Supplies",
      "Other Home Healthcare Products",
    ],
  },
  {
    name: "Patient Care Supplies",
    slug: "patient-care",
    isActive: true,
    subcategories: [
      "Bedpans",
      "Urinals",
      "Commode Chairs",
      "Patient Gowns",
      "Disposable Underpads",
      "Adult Incontinence Products",
      "Feeding Accessories",
      "Patient Hygiene",
      "Patient Positioning",
      "Patient Transfer Supplies",
      "Other Patient Care Products",
    ],
  },
  {
    name: "Medical Accessories & General Supplies",
    slug: "medical-accessories",
    isActive: true,
    subcategories: [
      "Medical Bags",
      "Equipment Bags",
      "Storage Containers",
      "Medical Trays",
      "Medical Bins",
      "Cables & Leads",
      "Replacement Parts",
      "Equipment Accessories",
      "Batteries",
      "Measuring Accessories",
      "General Medical Supplies",
      "Other Medical Accessories",
    ],
  },
];

export function subcategorySlug(name: string) {
  return name
    .toLowerCase()
    .replace(/&/g, "and")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}

